[build]
builder = "NIXPACKS"
buildCommand = "echo 'Using pre-built dist'"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/ping"
healthcheckTimeout = 100

[environments.production.deploy]
startCommand = "npm start"
